### ISSUE TITLE
Not working correctly when only one side swipable

### ISSUE THREAD

**Issue by cyril94440** [yammer/YMSwipeTableViewCell#6]
Hi again!

Really annoying issue :( 

When you add only on left view for example, you can easily completely block the cell by swiping one side then coming back to your original position without releasing the touch.

Here you can see the cells that are in that blocked state, not sure what is happening.

![capture d ecran 2016-02-19 a 15 56 49](https://cloud.githubusercontent.com/assets/2829562/13180828/05836da6-d722-11e5-98be-fd86f3583204.png)

**Comment by kerryknight** [comment]
Same problem here due to the nil left/right view checks [located here](https://github.com/yammer/YMSwipeTableViewCell/blob/master/YMSwipeTableViewCell/PodFiles/UITableViewCell%2BSwipe.m#L301-L307)

I worked around it by simply adding a view with no size to the side I do not wish to have an action/button attached to.  This isn't fully ideal as swiping is then enabled for that side and additional measures must be taken to lock it in place if desired.

**Comment by pwillsey** [comment]
Should be fixed thanks to @ppbdrinker
